// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUURdt-on9piPvPDh9u2_Svki2UvNAA50',
    appId: '1:755084894104:web:6f7ee2f2db473cccadd5ed',
    messagingSenderId: '755084894104',
    projectId: 'delel-f826b',
    authDomain: 'delel-f826b.firebaseapp.com',
    storageBucket: 'delel-f826b.appspot.com',
    measurementId: 'G-QLMLVTSDVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdfCLlYoKVvvmBoC_q4Khsyl8F6iyVUuo',
    appId: '1:755084894104:android:ce292a8abd8f919fadd5ed',
    messagingSenderId: '755084894104',
    projectId: 'delel-f826b',
    storageBucket: 'delel-f826b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtTdeY3V1kdiGYaDuZhEa9DZj7veSRl2Y',
    appId: '1:755084894104:ios:ff598b8313259242add5ed',
    messagingSenderId: '755084894104',
    projectId: 'delel-f826b',
    storageBucket: 'delel-f826b.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtTdeY3V1kdiGYaDuZhEa9DZj7veSRl2Y',
    appId: '1:755084894104:ios:ff598b8313259242add5ed',
    messagingSenderId: '755084894104',
    projectId: 'delel-f826b',
    storageBucket: 'delel-f826b.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUURdt-on9piPvPDh9u2_Svki2UvNAA50',
    appId: '1:755084894104:web:6197d0e4da2e076eadd5ed',
    messagingSenderId: '755084894104',
    projectId: 'delel-f826b',
    authDomain: 'delel-f826b.firebaseapp.com',
    storageBucket: 'delel-f826b.appspot.com',
    measurementId: 'G-JBF2CK7WE9',
  );
}
